import os
import sqlite3

DATABASE_URL = os.getenv("DATABASE_URL")
DEFAULT_DB_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "seed_checker.db"
)
DB_PATH = os.getenv("DATABASE_PATH", DEFAULT_DB_PATH)

if DATABASE_URL:
    import psycopg
    from psycopg.rows import dict_row


def normalize_seed_time(value):
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    parts = text.split(":")
    try:
        numbers = [int(part) for part in parts]
    except ValueError:
        return text
    if len(numbers) == 3:
        hours, minutes, seconds = numbers
    elif len(numbers) == 2:
        left, right = numbers
        if left <= 3 and len(parts[0]) == 1:
            hours, minutes, seconds = left, right, 0
        else:
            hours, minutes, seconds = 0, left, right
    else:
        return text
    if minutes > 59 or seconds > 59:
        return text
    if hours:
        return f"{hours}:{minutes:02d}:{seconds:02d}"
    return f"{minutes}:{seconds:02d}"


class PostgresConnection:
    def __init__(self):
        self.conn = psycopg.connect(DATABASE_URL, row_factory=dict_row)

    def execute(self, sql, params=None):
        return self.conn.execute(sql.replace("?", "%s"), params or ())

    def commit(self):
        self.conn.commit()

    def close(self):
        self.conn.close()


def get_db():
    if DATABASE_URL:
        return PostgresConnection()
    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA busy_timeout = 30000")
    return conn


def upsert_setting(conn, key, value):
    conn.execute(
        """
        INSERT INTO settings (key, value) VALUES (?, ?)
        ON CONFLICT(key) DO UPDATE SET value = excluded.value
        """,
        (key, str(value)),
    )


def init_postgres_db():
    conn = get_db()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS participants (
            registration_id TEXT PRIMARY KEY,
            first_name TEXT,
            last_name TEXT,
            age INTEGER,
            gender TEXT,
            city TEXT,
            state TEXT,
            uploaded_seed TEXT,
            runsignup_seed TEXT,
            runsignup_checked BOOLEAN NOT NULL DEFAULT FALSE,
            reviewed BOOLEAN NOT NULL DEFAULT FALSE,
            override_status TEXT
        )
    """)
    conn.execute(
        "ALTER TABLE participants ADD COLUMN IF NOT EXISTS reviewed BOOLEAN NOT NULL DEFAULT FALSE"
    )
    conn.execute("""
        CREATE TABLE IF NOT EXISTS past_results (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            race_id INTEGER NOT NULL,
            year INTEGER NOT NULL,
            event_id INTEGER NOT NULL,
            first_name TEXT,
            last_name TEXT,
            age INTEGER,
            gender TEXT,
            city TEXT,
            net_time TEXT,
            bib_number TEXT,
            race_name TEXT,
            event_name TEXT,
            distance TEXT,
            UNIQUE(race_id, event_id, first_name, last_name, age, gender)
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        )
    """)
    conn.execute(
        "UPDATE participants SET override_status = 'REVIEW' WHERE override_status = 'NEED TO GOOGLE'"
    )
    seed_defaults(conn)
    conn.commit()
    conn.close()


def seed_defaults(conn):
    conn.execute(
        """
        INSERT INTO settings (key, value) VALUES ('leeway_seconds', '300')
        ON CONFLICT(key) DO NOTHING
        """
    )
    defaults = {
        "race_id": "13089",
        "event_id": "1028766",
        "question_id": "7885",
        "race_name": "Boilermaker Road Race",
        "event_name": "15K Race - Presented By Excellus BlueCross BlueShield",
        "event_distance": "15K",
    }
    for key, value in defaults.items():
        conn.execute(
            """
            INSERT INTO settings (key, value) VALUES (?, ?)
            ON CONFLICT(key) DO NOTHING
            """,
            (key, value),
        )


def init_sqlite_db():
    conn = get_db()
    conn.execute("PRAGMA journal_mode = WAL")
    conn.execute("PRAGMA synchronous = NORMAL")
    participant_columns = {
        "registration_id",
        "first_name",
        "last_name",
        "age",
        "gender",
        "city",
        "state",
        "uploaded_seed",
        "runsignup_seed",
        "runsignup_checked",
        "reviewed",
        "override_status",
    }
    existing = {
        row["name"] for row in conn.execute("PRAGMA table_info(participants)").fetchall()
    }
    migrated_participants = not participant_columns.issubset(existing)
    if migrated_participants:
        conn.execute("""
            CREATE TABLE participants_new (
                registration_id TEXT PRIMARY KEY,
                first_name TEXT,
                last_name TEXT,
                age INTEGER,
                gender TEXT,
                city TEXT,
                state TEXT,
                uploaded_seed TEXT,
                runsignup_seed TEXT,
                runsignup_checked INTEGER NOT NULL DEFAULT 0,
                reviewed INTEGER NOT NULL DEFAULT 0,
                override_status TEXT
            )
        """)
        if existing:
            def source(column, fallback="NULL"):
                return column if column in existing else fallback

            uploaded = source("uploaded_seed", source("seed_time"))
            runsignup = source("runsignup_seed", source("rsu_seed_time"))
            checked = source(
                "runsignup_checked",
                f"CASE WHEN {runsignup} IS NULL THEN 0 ELSE 1 END",
            )
            reviewed = source("reviewed", "0")
            conn.execute(f"""
                INSERT INTO participants_new
                (registration_id, first_name, last_name, age, gender, city, state,
                 uploaded_seed, runsignup_seed, runsignup_checked, reviewed,
                 override_status)
                SELECT registration_id, first_name, last_name, age, gender, city, state,
                       {uploaded}, {runsignup}, {checked}, {reviewed},
                       {source("override_status")}
                FROM participants
            """)
            conn.execute("DROP TABLE participants")
        conn.execute("ALTER TABLE participants_new RENAME TO participants")

    conn.execute(
        "UPDATE participants SET override_status = 'REVIEW' WHERE override_status = 'NEED TO GOOGLE'"
    )
    if migrated_participants:
        rows = conn.execute(
            "SELECT registration_id, uploaded_seed, runsignup_seed FROM participants"
        ).fetchall()
        for row in rows:
            conn.execute(
                """
                UPDATE participants SET uploaded_seed = ?, runsignup_seed = ?
                WHERE registration_id = ?
                """,
                (
                    normalize_seed_time(row["uploaded_seed"]),
                    normalize_seed_time(row["runsignup_seed"]),
                    row["registration_id"],
                ),
            )

    past_sql_row = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name='past_results'"
    ).fetchone()
    past_sql = past_sql_row["sql"] if past_sql_row else ""
    if "UNIQUE(race_id, event_id" not in past_sql:
        conn.execute("""
            CREATE TABLE past_results_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                race_id INTEGER NOT NULL,
                year INTEGER NOT NULL,
                event_id INTEGER NOT NULL,
                first_name TEXT,
                last_name TEXT,
                age INTEGER,
                gender TEXT,
                city TEXT,
                net_time TEXT,
                bib_number TEXT,
                UNIQUE(race_id, event_id, first_name, last_name, age, gender)
            )
        """)
        if past_sql:
            existing_past = {
                row["name"]
                for row in conn.execute("PRAGMA table_info(past_results)").fetchall()
            }
            race_source = "race_id" if "race_id" in existing_past else "13089"
            bib_source = "bib_number" if "bib_number" in existing_past else "NULL"
            conn.execute(f"""
                INSERT INTO past_results_new
                (race_id, year, event_id, first_name, last_name, age, gender,
                 city, net_time, bib_number)
                SELECT COALESCE({race_source}, 13089), year, event_id,
                       first_name, last_name, age, gender, city, net_time, {bib_source}
                FROM past_results
                ON CONFLICT(race_id, event_id, first_name, last_name, age, gender)
                DO NOTHING
            """)
            conn.execute("DROP TABLE past_results")
        conn.execute("ALTER TABLE past_results_new RENAME TO past_results")
    for column in ("race_name TEXT", "event_name TEXT", "distance TEXT"):
        try:
            conn.execute(f"ALTER TABLE past_results ADD COLUMN {column}")
        except Exception:
            pass
    conn.execute("""
        UPDATE past_results
        SET race_name = COALESCE(race_name, 'Boilermaker Road Race'),
            distance = COALESCE(distance, '15K')
        WHERE race_id = 13089
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        )
    """)
    seed_defaults(conn)
    conn.commit()
    conn.close()


def init_db():
    if DATABASE_URL:
        init_postgres_db()
    else:
        init_sqlite_db()
